### ISSUE TITLE
Specify signature when replying/forwarding

### ISSUE THREAD

**Issue by Bouke** [jeevatkm/ReplyWithHeader#53]
Currently it's only possible to remove one's signature when replying/forwarding. My corporate signature is huge (including FB/twitter links). I would like to specify a condensed signature when replying, so I still don't have to type "Kind regards, /me, /function /corp". However as I have multiple e-mail accounts, I would have to select a different condensed signature when replying.

**Comment by Stradivaria** [comment]
After the upgrade to 5.2 Bèta and the release of 5.2 everything works great again!
Language location was an issue, glad you fixed it. Now, RWH is back an got rid of apple's lousy header ;-b
Just one remark: since updating to macos Sierra, the option for selecting reply signature is void. Used to work before under El Capitan. Re-adding the sigs in mail's preferences didn't change anything.
![rwh sig](https://cloud.githubusercontent.com/assets/23047450/19675254/828884e2-9a8d-11e6-8555-283514dff146.jpg)

**Comment by jeevatkm** [comment]
@Stradivaria Can you please create an separate new issue? we can continue our discussion in new thread.
